# Copyright (c) 2026, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
alloy_extra_groups:
  - mongod

alloy_log_paths:
  - path: /var/log/mongodb/mongod.log
    job: mongodb
