# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Install Redis exporter
  hosts: redis*
  become: true
  roles:
    - role: prometheus.prometheus.redis_exporter
      vars:
        redis_exporter_user: monitor
      tags: redis_exporter_install
  tasks:
    - name: Make custom configuration changes
      tags: redis_exporter_custom_config
      block:
        - name: Gather service facts
          ansible.builtin.service_facts:

        - name: Add CHECK_KEY_GROUPS to Redis exporter service file
          ansible.builtin.lineinfile:
            path: /etc/systemd/system/redis_exporter.service
            insertafter: '^\[Service\]'
            line: 'Environment="REDIS_EXPORTER_CHECK_KEY_GROUPS={{ prometheus_redis_exporter_check_key_groups }}"'
          when: prometheus_redis_exporter_check_key_groups is defined and prometheus_redis_exporter_check_key_groups | length > 0
          notify: Restart redis_exporter

        - name: Add CHECK_STREAMS to Redis exporter service file
          ansible.builtin.lineinfile:
            path: /etc/systemd/system/redis_exporter.service
            insertafter: 'Environment="REDIS_EXPORTER_CHECK_KEY_GROUPS={{ prometheus_redis_exporter_check_key_groups }}"'
            line: 'Environment="REDIS_EXPORTER_CHECK_STREAMS={{ prometheus_redis_exporter_check_streams }}"'
          when: prometheus_redis_exporter_check_streams is defined and prometheus_redis_exporter_check_streams | length > 0
          notify: Restart redis_exporter

        - name: Add MAX_DISTINCT_KEY_GROUPS to Redis exporter service file
          ansible.builtin.lineinfile:
            path: /etc/systemd/system/redis_exporter.service
            insertafter: 'Environment="REDIS_EXPORTER_CHECK_STREAMS={{ prometheus_redis_exporter_check_streams }}"'
            line: 'Environment="REDIS_EXPORTER_MAX_DISTINCT_KEY_GROUPS={{ prometheus_redis_exporter_max_distinct_key_groups }}"'
          when: prometheus_redis_exporter_max_distinct_key_groups is defined
          notify: Restart redis_exporter

        - name: Open Port on FirewallD Public Zone
          ansible.posix.firewalld:
            port: "{{ redis_exporter_web_listen_address.split(':') | last }}/tcp"
            permanent: true
            state: enabled
            zone: public
            immediate: true
          when:
            - ansible_facts.services["firewalld.service"] is defined
            - ansible_facts.services["firewalld.service"].state == "running"
            - ansible_facts.services["firewalld.service"].status == "enabled"

- name: Install MongoDB exporter
  hosts: mongodb*
  become: true
  roles:
    - role: prometheus.prometheus.mongodb_exporter
      vars:
        mongodb_exporter_collectors: all
      tags: mongodb_exporter_install
  tasks:
    - name: Make custom configuration changes
      tags: mongodb_exporter_custom_config
      block:

        - name: Add MongoDB authentication properties to MongoDB exporter
          when: mongodb_exporter_admin_password is defined
          notify: Restart mongodb_exporter
          block:

            - name: Add the MongoDB user to the systemd service file
              ansible.builtin.lineinfile:
                path: /etc/systemd/system/mongodb_exporter.service
                insertafter: '^\[Service\]'
                line: 'Environment="MONGODB_USER=admin"'

            - name: Add the MongoDB password to the systemd service file
              ansible.builtin.lineinfile:
                path: /etc/systemd/system/mongodb_exporter.service
                insertafter: 'Environment="MONGODB_USER=admin"'
                line: 'Environment="MONGODB_PASSWORD={{ mongodb_exporter_admin_password }}"'

        - name: Gather service facts
          ansible.builtin.service_facts:

        - name: Open Port on FirewallD Public Zone
          ansible.posix.firewalld:
            port: "{{ mongodb_exporter_web_listen_address.split(':') | last }}/tcp"
            permanent: true
            state: enabled
            zone: public
            immediate: true
          when:
            - ansible_facts.services["firewalld.service"] is defined
            - ansible_facts.services["firewalld.service"].state == "running"
            - ansible_facts.services["firewalld.service"].status == "enabled"

- name: Install node exporter
  hosts: redis*, mongodb*, platform*, gateway
  become: true
  roles:
    - role: prometheus.prometheus.node_exporter
      tags: node_exporter_install
  tasks:
    - name: Make custom configuration changes
      tags: node_exporter_custom_config
      block:
        - name: Gather service facts
          ansible.builtin.service_facts:

        - name: Open Port on FirewallD Public Zone
          ansible.posix.firewalld:
            port: "{{ node_exporter_web_listen_address.split(':') | last }}/tcp"
            permanent: true
            state: enabled
            zone: public
            immediate: true
          when:
            - ansible_facts.services["firewalld.service"] is defined
            - ansible_facts.services["firewalld.service"].state == "running"
            - ansible_facts.services["firewalld.service"].status == "enabled"

- name: Install process exporter
  hosts: platform*, gateway
  become: true
  roles:
    - role: prometheus.prometheus.process_exporter
      tags: process_exporter_install
  tasks:
    - name: Make custom configuration changes
      tags: process_exporter_custom_config
      block:
        - name: Gather service facts
          ansible.builtin.service_facts:

        - name: Open Port on FirewallD Public Zone
          ansible.posix.firewalld:
            port: "{{ process_exporter_web_listen_address.split(':') | last }}/tcp"
            permanent: true
            state: enabled
            zone: public
            immediate: true
          when:
            - ansible_facts.services["firewalld.service"] is defined
            - ansible_facts.services["firewalld.service"].state == "running"
            - ansible_facts.services["firewalld.service"].status == "enabled"
