{
 "title": "Itential High Level",
 "description": "This dashboard captures some of the high level metrics for the IAP system. It aggregates metrics from several different prometheus jobs.",
 "tags": [ "IAP" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(namedprocess_namegroup_context_switches_total,instance)"
    }
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(namedprocess_namegroup_context_switches_total,instance)"
    }
   },
   { "name": "iap_port", "query": "3000" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "processes",
    "label": "Processes",
    "query": {
     "query": "label_values(namedprocess_namegroup_num_procs,groupname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"${hostname}:9100\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"${hostname}:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"${hostname}:9100\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"${hostname}:9100\"} / node_memory_MemTotal_bytes{instance=\"${hostname}:9100\"})) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"${hostname}:9100\"} - node_memory_SwapFree_bytes{instance=\"${hostname}:9100\"}) / (node_memory_SwapTotal_bytes{instance=\"${hostname}:9100\"})) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"${hostname}:9100\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"${hostname}:9100\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "V8 Engine Heap Used",
   "type": "gauge",
   "description": "The percentage of the total V8 engine heap currently in use.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iap_memory_heap_usage_percentage{instance=\"${hostname}:${iap_port}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iap_active_jobs{instance=\"${hostname}:${iap_port}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total API Calls",
   "type": "stat",
   "description": "Total count of api calls since IAP start",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iap_total_api_calls{instance=\"${hostname}:${iap_port}\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "stat",
   "description": "The current number of logged in users",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iap_active_sessions{instance=\"${hostname}:${iap_port}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique Sessions",
   "type": "stat",
   "description": "The current number of logged in users",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iap_unique_sessions{instance=\"${hostname}:${iap_port}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"${hostname}:9100\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"${hostname}:9100\"}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "IAP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU time usage of IAP process",
   "type": "timeseries",
   "description": "CPU time usage of IAP process user vs system.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(iap_cpu_user_usage{instance=\"${hostname}:${iap_port}\"}[5m])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(iap_cpu_system_usage{instance=\"${hostname}:${iap_port}\"}[5m])",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Uptime Summary",
   "type": "table",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - namedprocess_namegroup_oldest_start_time_seconds{instance=~\"${hostname}:9256\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "V8 Engine Heap Total vs Size",
   "type": "timeseries",
   "description": "In a Node.js application, both \"heap size\" and \"heap used\" refer to aspects of the V8 JavaScript engine's memory management, specifically within the heap. The heap is a region of memory used for dynamic memory allocation, where objects and data structures whose size is not known at compile time are stored.\n\nHeap Size (or heapTotal):\n- This represents the total size of the memory heap that has been allocated and reserved by the V8 engine for the Node.js process.\n- It indicates the total amount of memory available for storing JavaScript objects, variables, and functions that are dynamically created during the application's execution.\n- This value can grow as the application requires more memory, up to a certain limit (which can be configured using flags like --max-old-space-size).\n\nHeap Used (heapUsed):\n- This represents the actual amount of memory currently being utilized within the allocated heap by the Node.js process.\n- It indicates how much of the heapTotal is actively holding live JavaScript objects and data.\n- The difference between heapTotal and heapUsed represents the free space available within the allocated heap.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "iap_total_memory_heap_size{instance=\"${hostname}:${iap_port}\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "iap_memory_heap_used_size{instance=\"${hostname}:${iap_port}\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Workflow Engine Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true
  },
  {
   "title": "CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Saturation and Max Core Usage",
     "type": "timeseries",
     "description": "When a system is running with maximum CPU utilization, the transmitting and receiving threads must all share the available CPU. This will cause data to be queued more frequently to cope with the lack of CPU. CPU Saturation may be measured as the length of a wait queue, or the time spent waiting on the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (instance) ((avg_over_time(node_procs_running{instance=~\"${hostname}:9100\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"${hostname}:9100\"})) or (avg_over_time(node_procs_running{instance=~\"${hostname}:9100\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"${hostname}:9100\"})))",
       "legendFormat": "Normalized CPU Load"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max(max by (instance) (sum  by (cpu,node_name) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"${hostname}:9100\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"${hostname}:9100\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max CPU Core Utilization"
      },
      {
       "expr": "avg by (instance) (aws_rds_cpu_credit_usage_average{instance=~\"${hostname}:9100\"})",
       "legendFormat": "CPU Credits Usage"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance,mode) (clamp_max(((avg by (mode,instance) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"${hostname}:9100\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"${hostname}:9100\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{instance=~\"${hostname}:9100\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"${hostname}:9100\", mode!=\"total\", mode!=\"idle\"}[5m]))),100))",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{instance=\"${hostname}:9100\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=\"${hostname}:9100\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=\"${hostname}:9100\"}",
       "legendFormat": "Load 15m"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (instance) ((avg_over_time(node_memory_MemTotal_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_MemTotal_bytes{instance=~\"${hostname}:9100\"}[5m])) + \n(avg_over_time(node_memory_SwapTotal_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_SwapTotal_bytes{instance=~\"${hostname}:9100\"}[5m])))",
       "legendFormat": "Total"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (instance) (\n(avg_over_time(node_memory_SwapFree_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_SwapFree_bytes{instance=~\"${hostname}:9100\"}[5m])) + ((avg_over_time(node_memory_MemAvailable_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_MemAvailable_bytes{instance=~\"${hostname}:9100\"}[5m])) or\n((avg_over_time(node_memory_MemFree_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_MemFree_bytes{instance=~\"${hostname}:9100\"}[5m]))+\n(avg_over_time(node_memory_Buffers_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_Buffers_bytes{instance=~\"${hostname}:9100\"}[5m]))+\n(avg_over_time(node_memory_Cached_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_Cached_bytes{instance=~\"${hostname}:9100\"}[5m]))))\n)",
       "legendFormat": "Available"
      },
      {
       "expr": "avg by (instance) (\n((avg_over_time(node_memory_MemTotal_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_MemTotal_bytes{instance=~\"${hostname}:9100\"}[5m])) +\n(avg_over_time(node_memory_SwapTotal_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_SwapTotal_bytes{instance=~\"${hostname}:9100\"}[5m]))) -\n((avg_over_time(node_memory_SwapFree_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_SwapFree_bytes{instance=~\"${hostname}:9100\"}[5m])) + ((avg_over_time(node_memory_MemAvailable_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_MemAvailable_bytes{instance=~\"${hostname}:9100\"}[5m])) or\n((avg_over_time(node_memory_MemFree_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_MemFree_bytes{instance=~\"${hostname}:9100\"}[5m]))+\n(avg_over_time(node_memory_Buffers_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_Buffers_bytes{instance=~\"${hostname}:9100\"}[5m]))+\n(avg_over_time(node_memory_Cached_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_Cached_bytes{instance=~\"${hostname}:9100\"}[5m])))))\n)",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (instance) (avg_over_time(node_memory_MemFree_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_MemFree_bytes{instance=~\"${hostname}:9100\"}[5m]))",
       "legendFormat": "Free"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (instance) (avg_over_time(node_memory_Buffers_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_Buffers_bytes{instance=~\"${hostname}:9100\"}[5m]))",
       "legendFormat": "Buffers"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_min(avg by (instance) (((avg_over_time(node_memory_MemTotal_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_MemTotal_bytes{instance=~\"${hostname}:9100\"}[5m])) - ((avg_over_time(node_memory_MemFree_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_MemFree_bytes{instance=~\"${hostname}:9100\"}[5m]))+ \n(avg_over_time(node_memory_Buffers_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_Buffers_bytes{instance=~\"${hostname}:9100\"}[5m])) + \n(avg_over_time(node_memory_Cached_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_Cached_bytes{instance=~\"${hostname}:9100\"}[5m]))))),0)",
       "legendFormat": "Used"
      },
      {
       "expr": "avg by (instance) (avg(avg_over_time(node_memory_Cached_bytes{instance=~\"${hostname}:9100\",job=~\"rds.*|node.*\"}[$interval]) or avg_over_time(node_memory_Cached_bytes{instance=~\"${hostname}:9100\",job=~\"rds.*|node.*\"}[5m])) without (job))",
       "legendFormat": "Cache"
      },
      {
       "expr": "avg by (instance) (avg_over_time(node_memory_MemTotal_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_MemTotal_bytes{instance=~\"${hostname}:9100\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Swap Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (instance) ((avg_over_time(node_memory_SwapTotal_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_SwapTotal_bytes{instance=~\"${hostname}:9100\"}[5m])) -\n(avg_over_time(node_memory_SwapFree_bytes{instance=~\"${hostname}:9100\"}[$interval]) or avg_over_time(node_memory_SwapFree_bytes{instance=~\"${hostname}:9100\"}[5m])))",
       "legendFormat": "Used"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (instance) (max_over_time(node_memory_SwapFree_bytes{instance=~\"${hostname}:9100\"}[$interval]) or max_over_time(node_memory_SwapFree_bytes{instance=~\"${hostname}:9100\"}[5m]))",
       "legendFormat": "Free"
      },
      {
       "expr": "avg by (instance) (max_over_time(node_memory_SwapTotal_bytes{instance=~\"${hostname}:9100\"}[$interval]) or max_over_time(node_memory_SwapTotal_bytes{instance=~\"${hostname}:9100\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Swap Activity",
     "type": "timeseries",
     "description": "Swap Activity is memory management that involves swapping sections of memory to and from physical storage.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (instance) (rate(node_vmstat_pswpin{instance=~\"${hostname}:9100\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=~\"${hostname}:9100\"}[5m]) * 4096)",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (instance) (rate(node_vmstat_pswpout{instance=~\"${hostname}:9100\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=~\"${hostname}:9100\"}[5m]) * 4096)",
       "legendFormat": "Swap Out (Writes)"
      },
      {
       "expr": "avg by (instance) ((rate(node_vmstat_pswpin{instance=~\"${hostname}:9100\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=~\"${hostname}:9100\"}[5m]) * 4096) + (rate(node_vmstat_pswpout{instance=~\"${hostname}:9100\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=~\"${hostname}:9100\"}[5m]) * 4096))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  { "title": "Web Server Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(iap_log_web_requests_total{instance=\"${hostname}:8000\"}[$__rate_interval]))",
     "legendFormat": "Total Request Rate"
    }
   ]
  },
  {
   "title": "Current Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iap_log_web_error_rate{instance=\"${hostname}:8000\"}",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Top 10 Endpoints by Request Rate",
   "type": "table",
   "description": "The top 10 requested URLs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(iap_log_web_endpoints_total{instance=\"${hostname}:8000\"}[$__rate_interval])) by (endpoint))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Users by Request Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(iap_log_web_users_total{instance=\"${hostname}:8000\"}[$__rate_interval])) by (user))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(iap_log_web_status_codes_total{instance=\"${hostname}:8000\"}[$__range])) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Endpoint Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(iap_log_web_endpoints_total{instance=\"${hostname}:8000\"}[$__range])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "Process and Thread Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Top processes by number of  processes instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,max_over_time(namedprocess_namegroup_num_procs{instance=~\"${hostname}:9256\"}[$interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by number of threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,max_over_time(namedprocess_namegroup_num_threads{instance=\"${hostname}:9256\"}[$interval]) )",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}